apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linguistai

resources:
  - namespace.yml
  - server-deployment.yml
  - server-service.yml
  - client-deployment.yml
  - client-service.yml
  - ingress.yml
  - hpa.yml

secretGenerator:
  - name: linguistai-secrets
    envs:
      - .env

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app.kubernetes.io/part-of: linguistai
  app.kubernetes.io/managed-by: kustomize
