apiVersion: v1
kind: Service
metadata:
  name: linguistai-server
  namespace: linguistai
  labels:
    app: linguistai
    component: server
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: linguistai
    component: server
